events {}

http {
    # Mapeo para Servidor 4 (example.local) - En webserv puerto 8080
    server {
        listen 8083;
        location / {
            proxy_pass http://webserv:8080;
            proxy_set_header Host example.local;
        }
    }

    # Mapeo para Servidor 2 (secondary.local) - En webserv puerto 8081
    server {
        listen 8084;
        location / {
            proxy_pass http://webserv:8081;
            proxy_set_header Host secondary.local;
        }
    }

    # Mapeo para Servidor 3 (restricted.local) - En webserv puerto 8082
    server {
        listen 8085;
        location / {
            proxy_pass http://webserv:8082;
            proxy_set_header Host restricted.local;
        }
    }

    # Mapeo para Servidor 1 (webserv.local) - En webserv puerto 8080
    server {
        listen 8086;
        location / {
            proxy_pass http://webserv:8080;
            proxy_set_header Host webserv.local;
        }
    }

    # Acceso por subrutas en el puerto 80 (Simulación visual)
    server {
        listen 80;

        # Nota: La barra '/' al final de proxy_pass es CRÍTICA
        # para que 'localhost/example' llegue como '/' a tu Webserv

        location /example/ {
            proxy_pass http://webserv:8080/;
            proxy_set_header Host example.local;
        }

        location /test/ {
            proxy_pass http://webserv:8080/;
            proxy_set_header Host test.local;
        }

        location /secondary/ {
            proxy_pass http://webserv:8081/;
            proxy_set_header Host secondary.local;
        }
    }
}
